/*****************************************************************************
 * @file        gpioDefs.c
 * @brief       GPIO definitions
 * @author      gruenzinger.stefan@gmail.com
 * @copyright   Copyright (c) 2020 Stefan Grünzinger
 *****************************************************************************
 */
#include "config/gpioDefs.h"

// clang-format off
halGpio_config_t gpioPortA[16] = {
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA0, -
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA1, -
    { HAL_GPIO_MODE_ALTERNATE, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF7_USART2, HAL_GPIO_INIT_RESET }, // PA2, Debug Serial TX, USART2
    { HAL_GPIO_MODE_ALTERNATE, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF7_USART2, HAL_GPIO_INIT_RESET }, // PA3, Debug Serial RX, USART2
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA4, SPI Ethernet CS, SPI1
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA5, SPI Ethernet SCK, SPI1
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA6, SPI Ethernet MISO, SPI1
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA7, SPI Ethernet MOSI, SPI1
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },        // PA8, InZistLeer_int 
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },        // PA9, InZist1_4_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },        // PA10, InZist1_2_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },        // PA11, InZistVoll_int
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA12, -
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PA13, JTAG SWDIO
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PA14, JTAG SWCLK
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },       // PA15, Relais 6
};

halGpio_config_t gpioPortB[16] = {
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PB0, -
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB1, -
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PB2, BOOT1
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PB3, SWO_TDO
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PB4, -
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PB5, -
    { HAL_GPIO_MODE_OUTPUT, HAL_GPIO_OUTPUT_TYPE_OPENDRAIN, HAL_GPIO_PULL_UP, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_SET },     // PB6, -
    { HAL_GPIO_MODE_OUTPUT, HAL_GPIO_OUTPUT_TYPE_OPENDRAIN, HAL_GPIO_PULL_UP, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_SET },     // PB7, -
    { HAL_GPIO_MODE_OUTPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB8, OutputData
    { HAL_GPIO_MODE_OUTPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB9, OutputClk
    { HAL_GPIO_MODE_OUTPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB10, OutputLatch
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PB11, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB12, EERPOM_SPI_CS
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB13, EEPROM_SPI_SCK
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB14, EEPROM_SPI_MISO
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PB15, EEPROM_SPI_MOSI
};

halGpio_config_t gpioPortC[16] = {
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC0, InAuto1_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC1, InAuto2_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC2, InAuto3_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC3, InHand1_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC4, InHand2_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC5, InHand3_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC6, InRegen_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC7, InWind_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC8, InExtra1_int
    { HAL_GPIO_MODE_INPUT, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },     // PC9, InExtra2_int
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PC10, FTDI_UART_TX
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PC11, FTDI_UART_RX
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PC12, -
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET },    // PC13, -
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PC14, OSC32
    { HAL_GPIO_MODE_UNCHANGED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PC15, OSC32
};

halGpio_config_t gpioPortD[16] = {
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD0, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD1, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD2, -
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD3, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD4, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD5, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD6, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD7, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD8, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD9, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD10, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD11, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD12, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD13, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD14, not available
    { HAL_GPIO_MODE_UNUSED, HAL_GPIO_OUTPUT_TYPE_PUSHPULL, HAL_GPIO_PULL_NO, HAL_GPIO_SPEED_HIGH, HAL_GPIO_AF_NONE, HAL_GPIO_INIT_RESET }, // PD15, not available
};
// clang-format on
